// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RetailBillingSystem.Data;

#nullable disable

namespace RetailBillingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507120136_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RetailBillingSystem.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3720),
                            FullName = "Store Admin",
                            IsActive = true,
                            PasswordHash = "GHVQ3kffbwHsr+Nln/uxAZ75bXZpTR06zEi8m96TMBg=",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("RetailBillingSystem.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GSTIN")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            City = "Bengaluru",
                            CreatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3680),
                            Email = "ravi@example.com",
                            GSTIN = "29ASHSS1234R1Z1",
                            IsActive = true,
                            Name = "Ravi Kumar",
                            Phone = "9876543210",
                            State = "Karnataka"
                        },
                        new
                        {
                            CustomerId = 2,
                            City = "Mysuru",
                            CreatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3688),
                            Email = "meena@traders.com",
                            GSTIN = "29BBBCA1557C1Z1",
                            IsActive = true,
                            Name = "Meena Traders",
                            Phone = "9123456789",
                            State = "Karnataka"
                        },
                        new
                        {
                            CustomerId = 3,
                            City = "Hubli",
                            CreatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3690),
                            IsActive = true,
                            Name = "Sunita Retail",
                            Phone = "9000000001",
                            State = "Karnataka"
                        });
                });

            modelBuilder.Entity("RetailBillingSystem.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceId"));

                    b.Property<string>("BuyerGSTIN")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<decimal>("CGSTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GSTType")
                        .HasColumnType("integer");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IGSTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("SGSTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalGST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("RetailBillingSystem.Models.InvoiceItem", b =>
                {
                    b.Property<int>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceItemId"));

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("GSTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GSTRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceItemId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("RetailBillingSystem.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GSTRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Groceries",
                            CreatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3248),
                            GSTRate = 5m,
                            IsActive = true,
                            LowStockThreshold = 10,
                            ProductName = "Basmati Rice 5kg",
                            Rate = 350m,
                            SKU = "SKU001",
                            StockQuantity = 150,
                            UpdatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3251)
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Groceries",
                            CreatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3260),
                            GSTRate = 5m,
                            IsActive = true,
                            LowStockThreshold = 10,
                            ProductName = "Tata Salt 1kg",
                            Rate = 22m,
                            SKU = "SKU002",
                            StockQuantity = 8,
                            UpdatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3261)
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Household",
                            CreatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3264),
                            GSTRate = 18m,
                            IsActive = true,
                            LowStockThreshold = 10,
                            ProductName = "Surf Excel 1kg",
                            Rate = 185m,
                            SKU = "SKU003",
                            StockQuantity = 60,
                            UpdatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3264)
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Personal Care",
                            CreatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3266),
                            GSTRate = 12m,
                            IsActive = true,
                            LowStockThreshold = 10,
                            ProductName = "Colgate Toothpaste",
                            Rate = 95m,
                            SKU = "SKU004",
                            StockQuantity = 45,
                            UpdatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3266)
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Household",
                            CreatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3269),
                            GSTRate = 18m,
                            IsActive = true,
                            LowStockThreshold = 10,
                            ProductName = "Ariel Detergent 2kg",
                            Rate = 310m,
                            SKU = "SKU005",
                            StockQuantity = 5,
                            UpdatedAt = new DateTime(2026, 5, 7, 12, 1, 36, 218, DateTimeKind.Utc).AddTicks(3270)
                        });
                });

            modelBuilder.Entity("RetailBillingSystem.Models.Invoice", b =>
                {
                    b.HasOne("RetailBillingSystem.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RetailBillingSystem.Models.InvoiceItem", b =>
                {
                    b.HasOne("RetailBillingSystem.Models.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailBillingSystem.Models.Product", "Product")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RetailBillingSystem.Models.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("RetailBillingSystem.Models.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RetailBillingSystem.Models.Product", b =>
                {
                    b.Navigation("InvoiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
