// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailBillingSystem.Data;

#nullable disable

namespace RetailBillingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RetailBillingSystem.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GSTIN")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            City = "Bengaluru",
                            CreatedAt = new DateTime(2026, 4, 18, 4, 50, 46, 450, DateTimeKind.Utc).AddTicks(3852),
                            Email = "ravi@example.com",
                            GSTIN = "29ASHSS1234R1Z1",
                            IsActive = true,
                            Name = "Ravi Kumar",
                            Phone = "9876543210",
                            State = "Karnataka"
                        },
                        new
                        {
                            CustomerId = 2,
                            City = "Mysuru",
                            CreatedAt = new DateTime(2026, 4, 18, 4, 50, 46, 450, DateTimeKind.Utc).AddTicks(3860),
                            Email = "meena@traders.com",
                            GSTIN = "29BBBCA1557C1Z1",
                            IsActive = true,
                            Name = "Meena Traders",
                            Phone = "9123456789",
                            State = "Karnataka"
                        },
                        new
                        {
                            CustomerId = 3,
                            City = "Hubli",
                            CreatedAt = new DateTime(2026, 4, 18, 4, 50, 46, 450, DateTimeKind.Utc).AddTicks(3862),
                            IsActive = true,
                            Name = "Sunita Retail",
                            Phone = "9000000001",
                            State = "Karnataka"
                        });
                });

            modelBuilder.Entity("RetailBillingSystem.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<string>("BuyerGSTIN")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("CGSTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GSTType")
                        .HasColumnType("int");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IGSTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("SGSTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalGST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("RetailBillingSystem.Models.InvoiceItem", b =>
                {
                    b.Property<int>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceItemId"));

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("GSTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GSTRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceItemId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("RetailBillingSystem.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GSTRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Groceries",
                            CreatedAt = new DateTime(2026, 4, 18, 4, 50, 46, 450, DateTimeKind.Utc).AddTicks(3613),
                            GSTRate = 5m,
                            IsActive = true,
                            LowStockThreshold = 10,
                            ProductName = "Basmati Rice 5kg",
                            Rate = 350m,
                            SKU = "SKU001",
                            StockQuantity = 150,
                            UpdatedAt = new DateTime(2026, 4, 18, 4, 50, 46, 450, DateTimeKind.Utc).AddTicks(3616)
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Groceries",
                            CreatedAt = new DateTime(2026, 4, 18, 4, 50, 46, 450, DateTimeKind.Utc).AddTicks(3624),
                            GSTRate = 5m,
                            IsActive = true,
                            LowStockThreshold = 10,
                            ProductName = "Tata Salt 1kg",
                            Rate = 22m,
                            SKU = "SKU002",
                            StockQuantity = 8,
                            UpdatedAt = new DateTime(2026, 4, 18, 4, 50, 46, 450, DateTimeKind.Utc).AddTicks(3624)
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Household",
                            CreatedAt = new DateTime(2026, 4, 18, 4, 50, 46, 450, DateTimeKind.Utc).AddTicks(3627),
                            GSTRate = 18m,
                            IsActive = true,
                            LowStockThreshold = 10,
                            ProductName = "Surf Excel 1kg",
                            Rate = 185m,
                            SKU = "SKU003",
                            StockQuantity = 60,
                            UpdatedAt = new DateTime(2026, 4, 18, 4, 50, 46, 450, DateTimeKind.Utc).AddTicks(3627)
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Personal Care",
                            CreatedAt = new DateTime(2026, 4, 18, 4, 50, 46, 450, DateTimeKind.Utc).AddTicks(3629),
                            GSTRate = 12m,
                            IsActive = true,
                            LowStockThreshold = 10,
                            ProductName = "Colgate Toothpaste",
                            Rate = 95m,
                            SKU = "SKU004",
                            StockQuantity = 45,
                            UpdatedAt = new DateTime(2026, 4, 18, 4, 50, 46, 450, DateTimeKind.Utc).AddTicks(3630)
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Household",
                            CreatedAt = new DateTime(2026, 4, 18, 4, 50, 46, 450, DateTimeKind.Utc).AddTicks(3631),
                            GSTRate = 18m,
                            IsActive = true,
                            LowStockThreshold = 10,
                            ProductName = "Ariel Detergent 2kg",
                            Rate = 310m,
                            SKU = "SKU005",
                            StockQuantity = 5,
                            UpdatedAt = new DateTime(2026, 4, 18, 4, 50, 46, 450, DateTimeKind.Utc).AddTicks(3632)
                        });
                });

            modelBuilder.Entity("RetailBillingSystem.Models.Invoice", b =>
                {
                    b.HasOne("RetailBillingSystem.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RetailBillingSystem.Models.InvoiceItem", b =>
                {
                    b.HasOne("RetailBillingSystem.Models.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailBillingSystem.Models.Product", "Product")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RetailBillingSystem.Models.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("RetailBillingSystem.Models.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RetailBillingSystem.Models.Product", b =>
                {
                    b.Navigation("InvoiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
